apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx-test
  namespace: argocd
spec:
  project: demo-project-test
  source:
    repoURL: https://github.com/kapildevops07/Test-ArgoCD-apache-nginxdeploy.git
    targetRevision: test
    path: helm-nginx
    helm:
      valueFiles:
        - ./helm-nginx/values-test.yml
      releaseName: test-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated: