apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-multiapp
  namespace: argocd
spec:
  project: demo-project
  source:
    repoURL: https://github.com/kapildevops07/Test-ArgoCD-apache-nginxdeploy.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - ./helm-nginx/values.yaml
        - ./helm-nginx/values-dev.yml
        - ./helm-nginx/values-test.yml
        - ./helm-apache/values.yaml
        - ./helm-apache/values-dev.yml
        - ./helm-apache/values-test.yml
      releaseName: Demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default