apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apache-dev
  namespace: argocd
spec:
  project: demo-project
  source:
    repoURL: https://github.com/kapildevops07/Test-ArgoCD-apache-nginxdeploy.git
    targetRevision: HEAD
    path: helm-apache
    helm:
      valueFiles:
        - helm-apache/values-dev.yml
      releaseName: dev-apache
  destination:
    server: https://kubernetes.default.svc
    namespace: dev